name = "caverco-partners-landing"
compatibility_date = "2024-09-01"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "caverco_contacts"
database_id = "7759c750-1fe4-474a-b3db-9c977c158bb4"
